export const PATHS = {
  root: "/",
  auth: {
    root: "/auth",
    login: "/auth/login",
    signup: "/auth/signup",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    verifyEmail: "/verify-email",
  },
  app: {
    account: "/account",
    askAi: "/ask-ai",
    billing: "/billing",
    calendar: "/calendar",
    help: "/help",
    home: "/",
    inbox: "/inbox",
    meetings: "/meetings",
    notifications: "/notifications",
    search: "/search",
    settings: "/settings",
    templates: "/templates",
    trash: "/trash",
  },
  projects: {
    root: "/projects",
    detail: (projectId: string) => `/projects/${projectId}`,
  },
  workspace: {
    root: "/workspace",
    create: "/workspace/create",
    department: "/workspace/department",
    teams: "/workspace/teams",
    plans: "/workspace/plans",
    members: "/workspace/members",
  },
  pages: {
    detail: (pageId: string) => `/p/${pageId}`,
    view: (pageId: string) => `/p/${pageId}`,
  },
  inbox: {
    detail: (chatRoomId: string) => `/inbox/${chatRoomId}`,
  },
  error: {
    root: "/error",
    notFound: "/error/404",
    server: "/error/500",
  },
} as const
